def display_win(window):
    frame()

def frame():
    print("###################################################################")
    print("#                                                                 #")
    print("#                                                                 #")
    print("#                                                                 #")
    print("#                                                                 #")
    print("#                                                                 #")
    print("#                                                                 #")
    print("#                                                                 #")
    print("#                                                                 #")
    print("#                                                                 #")
    print("#                                                                 #")
    print("#                                                                 #")
    print("#                                                                 #")
    print("#                                                                 #")
    print("#                                                                 #")
    print("#                                                                 #")
    print("###################################################################")